apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  ports:
    - port: 27017
      targetPort: 27017
      nodePort: 30002
      name: db-port
  selector:
    app: mongodb
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-dep
  labels:
    app: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      volumes:
      - name: mongo-data
        emptyDir: {}
      containers:
      - name: mongodb
        imagePullPolicy: IfNotPresent
        image: mongo:3.2
        ports:
        - containerPort: 27017
          name: db-port
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db