apiVersion: v1
kind: Service
metadata:
  name: jaeger
  labels:
    app: jaeger
spec:
  ports:
    - port: 16686
      targetPort: 16686
      nodePort: 30004
      name: jaeger-ui-port
    - port: 14268
      targetPort: 14268
      nodePort: 30005
      name: jaeger-port
  selector:
    app: jaeger
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger-dep
  labels:
    app: jaeger
spec:
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
      - name: jaeger
        image: jaegertracing/all-in-one:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 16686
          name: jaeger-ui-port
        - containerPort: 14268
          name: jaeger-port